// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RfpBackend.Data;

#nullable disable

namespace RfpBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206103809_AddVendorEmail")]
    partial class AddVendorEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RfpBackend.Models.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeliveryDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposalText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RfpId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RiskFactor")
                        .HasColumnType("REAL");

                    b.Property<int?>("SpecMatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warranty")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RfpId");

                    b.HasIndex("VendorId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("RfpBackend.Models.Rfp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeliveryDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rfps");
                });

            modelBuilder.Entity("RfpBackend.Models.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("RfpBackend.Models.Proposal", b =>
                {
                    b.HasOne("RfpBackend.Models.Rfp", "Rfp")
                        .WithMany("Proposals")
                        .HasForeignKey("RfpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfpBackend.Models.Vendor", "Vendor")
                        .WithMany("Proposals")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rfp");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("RfpBackend.Models.Rfp", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("RfpBackend.Models.Vendor", b =>
                {
                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
